// Code generated by mockery v2.44.1. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	protobuf "github.com/smousa/kafka-grpc-stream/protobuf"
)

// MockSenderStream is an autogenerated mock type for the SenderStream type
type MockSenderStream struct {
	mock.Mock
}

type MockSenderStream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSenderStream) EXPECT() *MockSenderStream_Expecter {
	return &MockSenderStream_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with given fields:
func (_m *MockSenderStream) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockSenderStream_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockSenderStream_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockSenderStream_Expecter) Context() *MockSenderStream_Context_Call {
	return &MockSenderStream_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockSenderStream_Context_Call) Run(run func()) *MockSenderStream_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSenderStream_Context_Call) Return(_a0 context.Context) *MockSenderStream_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSenderStream_Context_Call) RunAndReturn(run func() context.Context) *MockSenderStream_Context_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *MockSenderStream) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSenderStream_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockSenderStream_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockSenderStream_Expecter) RecvMsg(m interface{}) *MockSenderStream_RecvMsg_Call {
	return &MockSenderStream_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockSenderStream_RecvMsg_Call) Run(run func(m interface{})) *MockSenderStream_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockSenderStream_RecvMsg_Call) Return(_a0 error) *MockSenderStream_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSenderStream_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *MockSenderStream_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *MockSenderStream) Send(_a0 *protobuf.Message) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*protobuf.Message) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSenderStream_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSenderStream_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *protobuf.Message
func (_e *MockSenderStream_Expecter) Send(_a0 interface{}) *MockSenderStream_Send_Call {
	return &MockSenderStream_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *MockSenderStream_Send_Call) Run(run func(_a0 *protobuf.Message)) *MockSenderStream_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*protobuf.Message))
	})
	return _c
}

func (_c *MockSenderStream_Send_Call) Return(_a0 error) *MockSenderStream_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSenderStream_Send_Call) RunAndReturn(run func(*protobuf.Message) error) *MockSenderStream_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *MockSenderStream) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSenderStream_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockSenderStream_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockSenderStream_Expecter) SendHeader(_a0 interface{}) *MockSenderStream_SendHeader_Call {
	return &MockSenderStream_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *MockSenderStream_SendHeader_Call) Run(run func(_a0 metadata.MD)) *MockSenderStream_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockSenderStream_SendHeader_Call) Return(_a0 error) *MockSenderStream_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSenderStream_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *MockSenderStream_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *MockSenderStream) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSenderStream_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockSenderStream_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockSenderStream_Expecter) SendMsg(m interface{}) *MockSenderStream_SendMsg_Call {
	return &MockSenderStream_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockSenderStream_SendMsg_Call) Run(run func(m interface{})) *MockSenderStream_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockSenderStream_SendMsg_Call) Return(_a0 error) *MockSenderStream_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSenderStream_SendMsg_Call) RunAndReturn(run func(interface{}) error) *MockSenderStream_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *MockSenderStream) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSenderStream_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockSenderStream_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockSenderStream_Expecter) SetHeader(_a0 interface{}) *MockSenderStream_SetHeader_Call {
	return &MockSenderStream_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *MockSenderStream_SetHeader_Call) Run(run func(_a0 metadata.MD)) *MockSenderStream_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockSenderStream_SetHeader_Call) Return(_a0 error) *MockSenderStream_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSenderStream_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *MockSenderStream_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *MockSenderStream) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// MockSenderStream_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockSenderStream_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockSenderStream_Expecter) SetTrailer(_a0 interface{}) *MockSenderStream_SetTrailer_Call {
	return &MockSenderStream_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *MockSenderStream_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *MockSenderStream_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockSenderStream_SetTrailer_Call) Return() *MockSenderStream_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSenderStream_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *MockSenderStream_SetTrailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSenderStream creates a new instance of MockSenderStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSenderStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSenderStream {
	mock := &MockSenderStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
