// Code generated by mockery v2.44.1. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	metadata "google.golang.org/grpc/metadata"

	protobuf "github.com/smousa/kafka-grpc-stream/protobuf"
)

// MockBidiStream is an autogenerated mock type for the BidiStream type
type MockBidiStream struct {
	mock.Mock
}

type MockBidiStream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBidiStream) EXPECT() *MockBidiStream_Expecter {
	return &MockBidiStream_Expecter{mock: &_m.Mock}
}

// Context provides a mock function with given fields:
func (_m *MockBidiStream) Context() context.Context {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 context.Context
	if rf, ok := ret.Get(0).(func() context.Context); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	return r0
}

// MockBidiStream_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockBidiStream_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockBidiStream_Expecter) Context() *MockBidiStream_Context_Call {
	return &MockBidiStream_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockBidiStream_Context_Call) Run(run func()) *MockBidiStream_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBidiStream_Context_Call) Return(_a0 context.Context) *MockBidiStream_Context_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBidiStream_Context_Call) RunAndReturn(run func() context.Context) *MockBidiStream_Context_Call {
	_c.Call.Return(run)
	return _c
}

// Recv provides a mock function with given fields:
func (_m *MockBidiStream) Recv() (*protobuf.SubscribeRequest, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Recv")
	}

	var r0 *protobuf.SubscribeRequest
	var r1 error
	if rf, ok := ret.Get(0).(func() (*protobuf.SubscribeRequest, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *protobuf.SubscribeRequest); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*protobuf.SubscribeRequest)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockBidiStream_Recv_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Recv'
type MockBidiStream_Recv_Call struct {
	*mock.Call
}

// Recv is a helper method to define mock.On call
func (_e *MockBidiStream_Expecter) Recv() *MockBidiStream_Recv_Call {
	return &MockBidiStream_Recv_Call{Call: _e.mock.On("Recv")}
}

func (_c *MockBidiStream_Recv_Call) Run(run func()) *MockBidiStream_Recv_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBidiStream_Recv_Call) Return(_a0 *protobuf.SubscribeRequest, _a1 error) *MockBidiStream_Recv_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockBidiStream_Recv_Call) RunAndReturn(run func() (*protobuf.SubscribeRequest, error)) *MockBidiStream_Recv_Call {
	_c.Call.Return(run)
	return _c
}

// RecvMsg provides a mock function with given fields: m
func (_m *MockBidiStream) RecvMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for RecvMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBidiStream_RecvMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecvMsg'
type MockBidiStream_RecvMsg_Call struct {
	*mock.Call
}

// RecvMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockBidiStream_Expecter) RecvMsg(m interface{}) *MockBidiStream_RecvMsg_Call {
	return &MockBidiStream_RecvMsg_Call{Call: _e.mock.On("RecvMsg", m)}
}

func (_c *MockBidiStream_RecvMsg_Call) Run(run func(m interface{})) *MockBidiStream_RecvMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockBidiStream_RecvMsg_Call) Return(_a0 error) *MockBidiStream_RecvMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBidiStream_RecvMsg_Call) RunAndReturn(run func(interface{}) error) *MockBidiStream_RecvMsg_Call {
	_c.Call.Return(run)
	return _c
}

// Send provides a mock function with given fields: _a0
func (_m *MockBidiStream) Send(_a0 *protobuf.Message) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*protobuf.Message) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBidiStream_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockBidiStream_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 *protobuf.Message
func (_e *MockBidiStream_Expecter) Send(_a0 interface{}) *MockBidiStream_Send_Call {
	return &MockBidiStream_Send_Call{Call: _e.mock.On("Send", _a0)}
}

func (_c *MockBidiStream_Send_Call) Run(run func(_a0 *protobuf.Message)) *MockBidiStream_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*protobuf.Message))
	})
	return _c
}

func (_c *MockBidiStream_Send_Call) Return(_a0 error) *MockBidiStream_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBidiStream_Send_Call) RunAndReturn(run func(*protobuf.Message) error) *MockBidiStream_Send_Call {
	_c.Call.Return(run)
	return _c
}

// SendHeader provides a mock function with given fields: _a0
func (_m *MockBidiStream) SendHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SendHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBidiStream_SendHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendHeader'
type MockBidiStream_SendHeader_Call struct {
	*mock.Call
}

// SendHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockBidiStream_Expecter) SendHeader(_a0 interface{}) *MockBidiStream_SendHeader_Call {
	return &MockBidiStream_SendHeader_Call{Call: _e.mock.On("SendHeader", _a0)}
}

func (_c *MockBidiStream_SendHeader_Call) Run(run func(_a0 metadata.MD)) *MockBidiStream_SendHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockBidiStream_SendHeader_Call) Return(_a0 error) *MockBidiStream_SendHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBidiStream_SendHeader_Call) RunAndReturn(run func(metadata.MD) error) *MockBidiStream_SendHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SendMsg provides a mock function with given fields: m
func (_m *MockBidiStream) SendMsg(m interface{}) error {
	ret := _m.Called(m)

	if len(ret) == 0 {
		panic("no return value specified for SendMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBidiStream_SendMsg_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMsg'
type MockBidiStream_SendMsg_Call struct {
	*mock.Call
}

// SendMsg is a helper method to define mock.On call
//   - m interface{}
func (_e *MockBidiStream_Expecter) SendMsg(m interface{}) *MockBidiStream_SendMsg_Call {
	return &MockBidiStream_SendMsg_Call{Call: _e.mock.On("SendMsg", m)}
}

func (_c *MockBidiStream_SendMsg_Call) Run(run func(m interface{})) *MockBidiStream_SendMsg_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockBidiStream_SendMsg_Call) Return(_a0 error) *MockBidiStream_SendMsg_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBidiStream_SendMsg_Call) RunAndReturn(run func(interface{}) error) *MockBidiStream_SendMsg_Call {
	_c.Call.Return(run)
	return _c
}

// SetHeader provides a mock function with given fields: _a0
func (_m *MockBidiStream) SetHeader(_a0 metadata.MD) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for SetHeader")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(metadata.MD) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockBidiStream_SetHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetHeader'
type MockBidiStream_SetHeader_Call struct {
	*mock.Call
}

// SetHeader is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockBidiStream_Expecter) SetHeader(_a0 interface{}) *MockBidiStream_SetHeader_Call {
	return &MockBidiStream_SetHeader_Call{Call: _e.mock.On("SetHeader", _a0)}
}

func (_c *MockBidiStream_SetHeader_Call) Run(run func(_a0 metadata.MD)) *MockBidiStream_SetHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockBidiStream_SetHeader_Call) Return(_a0 error) *MockBidiStream_SetHeader_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBidiStream_SetHeader_Call) RunAndReturn(run func(metadata.MD) error) *MockBidiStream_SetHeader_Call {
	_c.Call.Return(run)
	return _c
}

// SetTrailer provides a mock function with given fields: _a0
func (_m *MockBidiStream) SetTrailer(_a0 metadata.MD) {
	_m.Called(_a0)
}

// MockBidiStream_SetTrailer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetTrailer'
type MockBidiStream_SetTrailer_Call struct {
	*mock.Call
}

// SetTrailer is a helper method to define mock.On call
//   - _a0 metadata.MD
func (_e *MockBidiStream_Expecter) SetTrailer(_a0 interface{}) *MockBidiStream_SetTrailer_Call {
	return &MockBidiStream_SetTrailer_Call{Call: _e.mock.On("SetTrailer", _a0)}
}

func (_c *MockBidiStream_SetTrailer_Call) Run(run func(_a0 metadata.MD)) *MockBidiStream_SetTrailer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(metadata.MD))
	})
	return _c
}

func (_c *MockBidiStream_SetTrailer_Call) Return() *MockBidiStream_SetTrailer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBidiStream_SetTrailer_Call) RunAndReturn(run func(metadata.MD)) *MockBidiStream_SetTrailer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBidiStream creates a new instance of MockBidiStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBidiStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBidiStream {
	mock := &MockBidiStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
