{
 "title": "Tuning Demo",
 "description": "Monitors for sizing and tuning kafka-grpc-stream servers",
 "tags": [ "examples" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "topic",
    "label": "Topic Name",
    "query": {
     "query": "label_values(kgs_active_sessions,topic)"
    }
   },
   {
    "name": "partition",
    "label": "Partition",
    "query": {
     "query": "label_values(kgs_active_sessions{topic=\"$topic\"},partition)"
    }
   },
   { "name": "server_instance", "label": "Server Instance", "query": "server" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service=~\"$server_instance.*\"}[$__rate_interval])",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_compose_service=~\"$server_instance.*\"}",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Dropped Messages Per Session Rate",
   "type": "stat",
   "description": "This metric takes the rate of total dropped messages and divides it by the the total number of active sessions on the provided host. A non-zero rate is an indicator that the broadcast buffer size needs to be increased.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "allIsZero" ] } },
   "targets": [
    {
     "expr": "rate(kgs_buffered_broadcast_dropped_messages{partition=\"$partition\", topic=\"$topic\"}[$__rate_interval]) / kgs_active_sessions",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Active Sessions",
   "type": "stat",
   "description": "Total number of active sessions across all servers.",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kgs_active_sessions{topic=\"$topic\", partition=\"$partition\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Evicted Message Age",
   "type": "candlestick",
   "description": "Tracks the min and max age of messages evicted from the buffer.  The age of the message is based on the kafka message timestamp not the timestamp that the server receives the message.",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - kgs_buffered_broadcast_eviction_timestamp_seconds{topic=\"$topic\", partition=\"$partition\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "downsampler": "min",
     "expression": "A",
     "type": "resample",
     "upsampler": "fillna",
     "window": "1m"
    },
    {
     "downsampler": "max",
     "expression": "A",
     "type": "resample",
     "upsampler": "fillna",
     "window": "1m"
    }
   ]
  },
  {
   "title": "Server Consumer Lag",
   "type": "timeseries",
   "description": "Consumer lag of the server against the topic partition.",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "clamp_min(\n  (max by(topic,partition) (max_over_time(redpanda_kafka_max_offset{topic=\"$topic\", partition=\"$partition\"}[5m]))) - on(topic,partition) group_left(instance) (max by(topic,partition,instance) (max_over_time(kgs_kafka_max_offset{topic=\"$topic\", partition=\"$partition\", instance=~\"$server_instance:\\\\d+\"}[5m]))),\n0)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Message In Rate",
   "type": "timeseries",
   "description": "Rate in which messages are ingested into kafka for all partitions.",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 16 },
   "targets": [
    {
     "expr": "rate(redpanda_kafka_records_produced_total{topic=\"$topic\"}[10m])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka Message In Bytes Rate",
   "type": "timeseries",
   "description": "Rate in which bytes are being produced for all partitions.",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(redpanda_kafka_request_bytes_total{redpanda_request=\"produce\", topic=\"$topic\"}[10m])",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}