with-expecter: true
packages:
  github.com/smousa/kafka-grpc-stream/internal/subscribe:
    config:
      dir: internal/mocks/subscribe
    interfaces:
      KafkaClient:
      Publisher:
  github.com/smousa/kafka-grpc-stream/internal/service:
    config:
      dir: internal/mocks/service
    interfaces:
      SenderStream:
      BidiStream:
      SessionRegistry:
