services:
  etcd:
    image: bitnami/etcd:3.5.15
    environment:
      ALLOW_NONE_AUTHENTICATION: yes
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd:2379

  server:
    stop_signal: SIGINT
    depends_on:
      - etcd
    build:
      context: .
      args:
        ALPINE_VERSION: ${ALPINE_VERSION}
        GOLANG_VERSION: ${GOLANG_VERSION}
        LINTER_VERSION: ${LINTER_VERSION}
        COVER_VERSION: ${COVER_VERSION}
        MOCKERY_VERSION: ${MOCKERY_VERSION}
    environment:
      - ETCD_ENDPOINTS=etcd:2379
      - LISTEN_URL=0.0.0.0:9000
      - LISTEN_ADVERTISE_URL=server:9000
      - WORKER_TOPIC=my.test.topic
      - WORKER_PARTITION=0
      - WORKER_LEASE_EXPIRY_SECONDS=30


  etcd-dev:
    profiles:
      - ci
    extends:
      service: etcd
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: http://etcd-dev:2379
  dev:
    profiles:
      - ci
    extends:
      service: server
    depends_on:
      - etcd-dev
    build:
      context: .
      target: base
    environment:
      - ETCD_ENDPOINTS=etcd-dev:2379
    volumes:
      - .:/workspace
