name: Merge

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    permissions: write-all
    name: Release
    runs-on: [ ubuntu-latest ]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: load settings
        id: settings
        shell: bash
        run: |
          echo BUILD_VERSION=$(cat VERSION) >> $GITHUB_OUTPUT
      - name: create tag
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ steps.settings.outputs.BUILD_VERSION }}',
              sha: context.sha
            })

  push:
    name: Push
    runs-on: [ ubuntu-latest ]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: load settings
        id: settings
        shell: bash
        run: |
          cat .env >> $GITHUB_OUTPUT
          echo BUILD_VERSION=$(cat VERSION) >> $GITHUB_OUTPUT
          echo BUILD_DATE=$(date '+%Y%m%d') >> $GITHUB_OUTPUT
          echo BUILD_COMMIT=$(git rev-parse --short HEAD) >> $GITHUB_OUTPUT
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: log into docker hub
        uses: docker/login-action@v3
        with: ${{ fromJSON(secrets.DOCKER_HUB) }}
      - name: build
        uses: docker/build-push-action@v6
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |-
            ALPINE_VERSION=${{ steps.settings.outputs.ALPINE_VERSION }}
            GOLANG_VERSION=${{ steps.settings.outputs.GOLANG_VERSION }}
            LINTER_VERSION=${{ steps.settings.outputs.LINTER_VERSION }}
            COVER_VERSION=${{ steps.settings.outputs.COVER_VERSION }}
            MOCKERY_VERSION=${{ steps.settings.outputs.MOCKERY_VERSION }}
            BUILD_VERSION=${{ steps.settings.outputs.BUILD_VERSION }}
            BUILD_DATE=${{ steps.settings.outputs.BUILD_DATE }}
            BUILD_COMMIT=${{ steps.settings.outputs.BUILD_COMMIT }}
          tags: |-
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.settings.outputs.BUILD_VERSION }}
