name: Pull Request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Test
    runs-on: [ ubuntu-latest ]
    container:
      image: ${{ github.event.repository.name }}:base
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: lint
        run: make lint
        shell: bash
      - name: test
        shell: bash
        run: make test
      - name: coverage
        shell: bash
        run: make coverage
      - name: clean
        if: always()
        shell: bash
        run: make clean

  build:
    name: Build
    runs-on: [ ubuntu-latest ]
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: load settings
        id: settings
        shell: bash
        run: |
          make version
          cat .env >> $GITHUB_OUTPUT
          echo BUILD_VERSION=$(cat VERSION) >> $GITHUB_OUTPUT
          echo BUILD_DATE=$(date '+%Y%m%d') >> $GITHUB_OUTPUT
          echo BUILD_COMMIT=$(git rev-parse --short HEAD)
      - name: set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: build
        uses: docker/build-push-action@v6
        with:
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ALPINE_VERSION=${{ steps.settings.outputs.ALPINE_VERSION }}
            GOLANG_VERSION=${{ steps.settings.outputs.GOLANG_VERSION }}
            LINTER_VERSION=${{ steps.settings.outputs.LINTER_VERSION }}
            COVER_VERSION=${{ steps.settings.outputs.COVER_VERSION }}
            MOCKERY_VERSION=${{ steps.settings.outputs.MOCKERY_VERSION }}
            BUILD_VERSION=${{ steps.settings.outputs.BUILD_VERSION }}
            BUILD_DATE=${{ steps.settings.outputs.BUILD_DATE }}
            BUILD_COMMIT=${{ steps.settings.outputs.BUILD_COMMIT }}
          tags: |
            ${{ github.repository }}
            ${{ github.repository }}:${{ steps.settings.outputs.BUILD_VERSION }}
